name: Stage Deployment

on: [push]

jobs:
  build:
    name: deploy to staging

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install

    - name: Run test suite
      run: composer run-script test
